### ISSUE TITLE
Calling calc_route_info() results in JSONDecodeError

### ISSUE THREAD

**Issue by gkhartman** [kovacsbalu/WazeRouteCalculator#16]
Update: When looking deeper I noticed that the request in get_routes() returns a 403 error response.

Here's the error message at the bottom of the resulting stack trace:
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
This code should reproduce the error (confirmed on python 2.7):
```python
import WazeRouteCalculator


from_address = 'Los Angeles, CA'
to_address = 'San Fransisco, CA'
region = 'US'
route = WazeRouteCalculator.WazeRouteCalculator(from_address, to_address, region)
print route.calc_route_info()
```

**Comment by Petro31** [comment]
This is actually occurring quite frequently now with valid data.

**Comment by kovacsbalu** [comment]
Hi, actually looks good. Can you please get some debug info or stack trace? What is in the response?

**Comment by gkhartman** [comment]
@kovacsbalu I ran request code found in the WazeRoutCalculator.get_route method and have printed the GET response (It's a code 403 response). Here's the code with output that includes the json parsing stack trace at the bottom:
Code:
```python
import requests


url_options = {
        "from": "x:%s y:%s" % ('-118.144', '34.178'),
        "to": "x:%s y:%s" % ('-118.244', '34.052'),
        "at": 0,
        "returnJSON": "true",
        "returnGeometries": "true",
        "returnInstructions": "true",
        "timeout": 60000,
        "nPaths": 1,
        "options": "AVOID_TRAILS:t",}

headers = {'referer': 'https://www.waze.com'}

response = requests.get('https://www.waze.com/RoutingManager/routingRequest', params=url_options, headers=headers)

print("Response:")
print(response)

print("Response Content:")
print(response.content)

print("Response JSON:")
print(response.json())
```
Output:
```
Response:
<Response [403]>
Response Content:
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

Response JSON:
Traceback (most recent call last):
  File "test_waze_package_issue.py", line 34, in <module>
    print(response.json())
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
It could be that the request is rejected by the server due to a missing User Agent or session token. Also, note that I'm running this with the US version of request URL (if it wasn't obvious from the code).

**Comment by Petro31** [comment]
Also running from US.  Home Assistant has a user that is using IL that has the same issue though.
