### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by BonoVanderpoorten** [kovacsbalu/WazeRouteCalculator#21]
Hey,

Thanks a lot for the API, been using it off and on for a while. Wanted to use it this week and saw this error trace getting thrown with the simple scripts I've written. (Tbh it's your quickstart script with changed hardcoded locations nothing big really)
And I've been getting this:

```
PS C:\Users\X\Github\WazeRouteCalculator> python .\NamurHome.py
From: Namur - to: Lokeren, België
Traceback (most recent call last):
  File ".\NamurHome.py", line 9, in <module>
    route.calc_route_info()
  File "C:\Users\X\Github\WazeRouteCalculator\WazeRouteCalculator\WazeRouteCalculator.py", line 133, in calc_route_info
    route = self.get_route(1, time_delta)
  File "C:\Users\X\Github\WazeRouteCalculator\WazeRouteCalculator\WazeRouteCalculator.py", line 92, in get_route
    response_json = response.json()
  File "C:\Python34\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

Am I missing something obvious here?

Kind Regards,

**Comment by kovacsbalu** [comment]
Hi @BonoVanderpoorten,
can you please print your WRC version?
```
import WazeRouteCalculator
print(WazeRouteCalculator.__version__)
```

**Comment by BonoVanderpoorten** [comment]
Hey @kovacsbalu 

This is kinda weird, since I ran `pip install WazeRouteCalculator` and it showed version 0.6 got installed so I thought I was updated. I'll figure out how to update, sorry for the fake issue!

```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import WazeRouteCalculator
>>> print(WazeRouteCalculator.__version__)
0.5
```
