### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by djdevil** [kovacsbalu/WazeRouteCalculator#75]
i tried to run the sample python i get the same error, can you confirm that maybe something has changed in the api?

From: Budapest, Hungary - to: Győr, Hungary
Start coords: (47.467660814, 19.077617881)
End coords: (47.67936706542969, 17.707035064697266)
Internal Error

**Comment by kovacsbalu** [comment]
It works for me:
```From: Budapest, Hungary - to: Győr, Hungary
Start coords: (47.467660814, 19.077617881)
End coords: (47.6793670654, 17.7070350647)
Time 79.53 minutes, distance 118.27 km.```

**Comment by asucrews** [comment]
I get the same issue. could this be a case that pip version is not update with the master? i see there was changes on aug 2022 but no version release?

**Comment by asucrews** [comment]
i get the error on master as well

it must be what i am doing.  what is the correct format for inter GPS cords as the start and finish address?

**Comment by kovacsbalu** [comment]
Can you please show your code? 
The from and to should be "City, Country"  as address.
or you can use coords as the test shows: https://github.com/kovacsbalu/WazeRouteCalculator/blob/master/tests.py#L60

**Comment by RobSpectre** [comment]
Getting this issue as well.  Example:

```
>>> route = WazeRouteCalculator.WazeRouteCalculator("40.758657348999,-73.98539239629918", "37.80310697872614,-122.40541450424061", "US")
>>> route.calc_route_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rspectre/.virtualenvs/baker/lib/python3.10/site-packages/WazeRouteCalculator/WazeRouteCalculator.py", line 199, in calc_route_info
    route = self.get_route(1, time_delta)
  File "/home/rspectre/.virtualenvs/baker/lib/python3.10/site-packages/WazeRouteCalculator/WazeRouteCalculator.py", line 142, in get_route
    raise WRCError(response_json.get("error"))
WazeRouteCalculator.WazeRouteCalculator.WRCError: Internal Error
```

Also tried passing `region` as "NA" to no avail.

**Comment by RobSpectre** [comment]
Debugging this a bit, appears to be coming from Waze itself.

Looking at the response in pdb, all Waze is returning is `{'error': 'Internal Error'}`.

**Comment by RobSpectre** [comment]
Debugging this more, I think the route was just too long. In the waze app such a route also silently dies without a helpful error message.

**Comment by kovacsbalu** [comment]
Too long route, unknown destination point, rate limit. Unfortunately no detailed info about the error.
Sometimes re-run is enough (probably rate limit)
